WebLibrary/Models/UserInfoViewModel.cs
using BusinessLogic.DTOs;

namespace WebLibrary.Models
{
    public class UserInfoViewModel
    {
        public BankAccountDto BankAccount { get; set; }
        public string UserFirstName { get; set; }
        public string UserSex { get; set; }
        public string UserLastName { get; set; }
        public bool UnconfirmedCredit { get; set; }
        public LoanDto LastLoan { get; set; }
        public int? LoansTaken { get; set; }
        public CreditDto ActiveCredit { get; set; }

        public string IconClass
        {
            get
            {
                if (UserSex == "Female")
                    return "icon-woman";
                else
                    return "icon-man";
            }
        }

        public int LoanProgressBar
        {
            get
            {
                if (LastLoan == null)
                    return 0;
                else
                    return (int)(100 * (LastLoan.TotalInstallments - LastLoan.InstallmentsLeft) / LastLoan.TotalInstallments);
            }
        }

        public int CreditProgressBar
        {
            get
            {
                if (ActiveCredit == null)
                    return 0;
                else
                    return 100 * ActiveCredit.InstallmentsAlreadyPaid / ActiveCredit.InstallmentCount;
            }
        }
    }
}

WebLibrary/Controllers/CreditsController.cs
using BusinessLogic.Interfaces;
using System.Web.Mvc;
using WebLibrary.IdentityExtensions;

namespace WebLibrary.Controllers
{
    [Authorize]
    public class CreditsController : Controller
    {
        private readonly ICreditService _creditService;

        public CreditsController(ICreditService creditService)
        {
            _creditService = creditService;
        }

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId().Value;
            var credits = _creditService.GetCredits(userId).Data;

            return View(credits);
        }

        public ActionResult ObtainCredit()
        {
            return View();
        }

        public ActionResult InstallmentsPage(int Id)
        {
            var userId = User.Identity.GetUserId().Value;
            var creditInfo = _creditService.GetCreditInfo(userId, Id);

            if (!creditInfo.Success)
                return RedirectToAction("Index", "UserInfo");
            else
                return View(creditInfo.Data);
        }

        [HttpPost]
        public ActionResult ConfirmCredit()
        {
            var userId = User.Identity.GetUserId().Value;

            _creditService.ConfirmCredit(userId);

            return RedirectToAction("Index", "UserInfo");
        }

        public ActionResult CreditHistory()
        {
            var userId = User.Identity.GetUserId().Value;

            var credits = _creditService.GetCredits(userId).Data;

            return View(credits);
        }
    }
}

WebLibrary/Controllers/UserInfoController.cs
using BusinessLogic.Interfaces;
using System.Linq;
using System.Web.Mvc;
using WebLibrary.IdentityExtensions;
using WebLibrary.Models;

namespace WebLibrary.Controllers
{
    [Authorize]
    public class UserInfoController : Controller
    {
        private readonly IBankAccountService _bankAccountService;
        private readonly ILoanService _loanService;
        private readonly ICreditService _creditService;

        public UserInfoController(IBankAccountService bankAccountService, ILoanService loanService, ICreditService creditService)
        {
            _bankAccountService = bankAccountService;
            _loanService = loanService;
            _creditService = creditService;
        }

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId().Value;
            var bankAccount = _bankAccountService.GetBankAccountDetails(userId);

            if (bankAccount == null)
            {
                return RedirectToAction("Create", "BankAccount");
            }

            var sex = User.Identity.GetUserSex();
            var lastName = User.Identity.GetUserLastName();
            var loans = _loanService.GetLoans(userId);
            var lastLoan = loans.Where(l => l.InstallmentsLeft > 0).OrderBy(l => l.DateTaken).FirstOrDefault();
            var activeCredit = _creditService.HasActiveCredit(userId);

            var userInfo = new UserInfoViewModel()
            {
                BankAccount = bankAccount,
                UserFirstName = User.Identity.Name,
                UserLastName = lastName,
                UserSex = sex,
                UnconfirmedCredit = _bankAccountService.HasUnconfirmedCredit(userId),
                LastLoan = lastLoan,
                LoansTaken = loans.Count,
                ActiveCredit = activeCredit.Success ? activeCredit.Data : null
            };
            return View(userInfo);
        }
    }
}

WebLibrary/Views/UserInfo/Index.cshtml
@model WebLibrary.Models.UserInfoViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="accountInfoModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5>Account's transfers statistics</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="text-danger">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div class="alert alert-danger text-center">
                            You've made
                            <span class="font-weight-bold" id="js-transfers-sent"></span>
                            transfers, <br />sending
                            <span class="font-weight-bold" id="js-total-money-sent"></span>
                            PLN in total.
                        </div>
                    </div>

                    <div class="col">
                        <div class="alert alert-success text-center">
                            You've been sent
                            <span class="font-weight-bold" id="js-transfers-received"></span>
                            transfers, <br />receiving
                            <span class="font-weight-bold" id="js-total-money-received"></span>
                            PLN in total.
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <canvas id="js-transfer-chart" width="400" height="400"></canvas>
                </div>

            </div>
        </div>
    </div>
</div>

@if (Model.UnconfirmedCredit)
{
    <div class="alert alert-info text-center mt-2" role="alert">
        <strong>We have received your credit request and it's currently being processed.</strong>
        <form method="post" action="@Url.Action("ConfirmCredit", "Credits")">
            <button class="btn btn-primary btn-sm" type="submit"></button>
        </form>
    </div>
}

<div class="row mt-5">
    @*Account's info*@
    <div class="col-4 px-2">
        <div class="container h-100 jumbotron px-4 mb-0 visibility3">
            <div class="row mb-3">
                <div class="col">
                    <div class=@Model.IconClass></div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h2>@Model.UserFirstName @Model.UserLastName</h2>
                </div>
            </div>
            <hr />
            <div class="row my-3 mx-0">
                <div class="col px-0">
                    <h4><span class="float-left">Account type:</span></h4>
                </div>
                <div class="col px-0">
                    <h4><span class="float-right">@Model.BankAccount.BankAccountType</span></h4>
                </div>
            </div>

            <div class="row my-3 mx-0">
                <div class="col px-0">
                    <h4><span class="float-left">Balance:</span></h4>
                </div>
                <div class="col px-0">
                    <h4><span class="float-right">@Model.BankAccount.Cash PLN</span></h4>
                </div>
            </div>

            <div class="row my-3 mx-0">
                <div class="col px-0">
                    <span class="float-left">Account's ID</span>
                </div>
                <div class="col px-0">
                    <span class="float-right">@Model.BankAccount.Id</span>
                </div>
            </div>
            <div class="row my-3 mx-0">
                <div class="col px-0">
                    <span class="float-left">Loans taken:</span>
                </div>
                <div class="col px-0">
                    <span class="float-right">@Model.LoansTaken</span>
                </div>
            </div>

            <div class="row my-3 mx-0">
                <div class="col px-0">
                    <span class="float-left">Investments:</span>
                </div>
                <div class="col px-0">
                    <span class="float-right">2</span>
                </div>
            </div>

            <hr />
            <div class="row mx-0 justify-content-end">
                <a href="#" data-toggle="modal" data-target="#accountInfoModal">See more...</a>
            </div>


        </div>

    </div>

    @*Loans info*@
    <div class="col-8 px-0">
        <div class="container d-flex h-100 flex-column mb-0 pb-0">
            <div class="container jumbotron px-4 pb-3 mb-3 mt-auto visibility3 flex-grow-1">

                @if (Model.LastLoan == null)
                {
                    <h2>You don't have any active loan right now</h2>
                    <hr />
                    <p>You will see info about it here</p>
                }
                else
                {
                    <h2>Your last loan!</h2>
                    <hr />
                    <div class="row my-3 mx-0">
                        <div class="col px-0">
                            <span class="float-left"><strong>Credit amount:</strong> @Model.LastLoan.LoanAmount</span>
                        </div>

                        <div class="col px-0">
                            <span class="float-left"><strong>Amount left:</strong> @Model.LastLoan.LoanAmountLeft</span>
                        </div>

                        <div class="col px-0">
                            <span class="float-right"><strong>Installments left:</strong> @Model.LastLoan.InstallmentsLeft</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col progress">
                            <div class="progress-bar bg-success h-25" style="width: @(Model.LoanProgressBar)%" role="progressbar" aria-valuemin="0" aria-valuemax="@Model.LastLoan.TotalInstallments"></div>
                        </div>
                    </div>
                }

                <hr />
                <div class="row mx-0 justify-content-end"><a href="#">See more...</a></div>
            </div>

            @*Credits info*@

            <div class="container jumbotron px-4 pb-3 mt-2 mb-auto visibility3 flex-grow-1">
                @if (Model.ActiveCredit == null)
                {
                    <h2>You don't have an active credit right now</h2>
                    <hr />
                    <p>You will see info about it here</p>
                }
                else
                {
                    <h2>Your active credit</h2>
                    <hr />
                    <div class="row justify-content-center my-3 mx-0">
                        <div class="col px-0">
                            <span class="float-left"><strong>Credit amount:</strong> @Model.ActiveCredit.CreditAmount PLN</span>
                        </div>
                        <div class="col px-0">
                            <span class="float-left"><strong>Percentage rate:</strong> @Model.ActiveCredit.PercentageRate%</span>
                        </div>
                        <div class="col px-0">
                            <span class="float-right"><strong>Credit period:</strong> @(Model.ActiveCredit.InstallmentCount / 12) year(s)</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col progress">
                            <div class="progress-bar bg-success h-25" style="width: @(Model.CreditProgressBar)%" role="progressbar" aria-valuemin="0" aria-valuemax="@Model.ActiveCredit.InstallmentCount"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <span>@Model.ActiveCredit.InstallmentsAlreadyPaid out of @Model.ActiveCredit.InstallmentCount installments already paid</span>
                        </div>
                    </div>
                }


                <hr />
                <div class="row mx-0 justify-content-end"><a href="#">See more...</a></div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript" src="~/Scripts/Chart.min.js"></script>
    <script type="text/javascript" src="~/Scripts/app/userInfo/index.js"></script>

}