WebLibrary/Models/BankAccountViewModel.cs
using BusinessLogic.DTOs;
using System.Collections.Generic;

namespace WebLibrary.Models
{
    public class BankAccountViewModel
    {
        public IEnumerable<BankAccountTypeDto> BankAccountTypes { get; set; }
        public BankAccountDto BankAccountDto { get; set; }
    }
}

WebLibrary/Controllers/BankAccountController.cs
using BusinessLogic.DTOs;
using BusinessLogic.Interfaces;
using System.Web.Mvc;
using WebLibrary.IdentityExtensions;
using WebLibrary.Models;

namespace WebLibrary.Controllers
{
    [Authorize]
    public class BankAccountController : Controller
    {
        private readonly IBankAccountService _bankAccountService;
        private readonly IBankAccountTypeService _bankAccountTypeService;

        public BankAccountController(IBankAccountService bankAccountService, IBankAccountTypeService bankAccountTypeService)
        {
            _bankAccountService = bankAccountService;
            _bankAccountTypeService = bankAccountTypeService;
        }

        public ActionResult Create()
        {
            if (_bankAccountService.UserAlreadyHasAccount(User.Identity.GetUserId().Value))
                return RedirectToAction("Index", "UserInfo");
            else
            {
                var bankAccountTypes = _bankAccountTypeService.GetBankAccountTypes();
                return View(new BankAccountViewModel() { BankAccountTypes = bankAccountTypes, BankAccountDto = new BankAccountDto() });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BankAccountViewModel bankAccountViewModel)
        {
            var currentUserId = User.Identity.GetUserId().Value;

            if (_bankAccountService.UserAlreadyHasAccount(currentUserId))
                return RedirectToAction("Index", "UserInfo");

            if (!ModelState.IsValid)
                return View(bankAccountViewModel);

            var bankAccountDto = new BankAccountDto()
            {
                ApplicationUserId = currentUserId,
                BankAccountTypeId = bankAccountViewModel.BankAccountDto.BankAccountTypeId,
            };
            _bankAccountService.CreateBankAccount(bankAccountDto);

            return RedirectToAction("Index", "UserInfo");
        }
    }
}

WebLibrary/Views/BankAccount/Create.cshtml
@model WebLibrary.Models.BankAccountViewModel
@using (Html.BeginForm("Create", "BankAccount"))
{
    @Html.AntiForgeryToken();
    <div class="row justify-content-center">
        <div class="jumbotron py-5 mt-5 visibility3">
            <h3 class="text-center">Set up a bank account</h3>
            <hr />
            <div class="form-group">
                @Html.DropDownListFor(m => m.BankAccountDto.BankAccountTypeId,
               new SelectList(Model.BankAccountTypes, "Id", "Name"),
               "Choose account type", new { @class = "form-control" })
            </div>
            <input type="submit" class="btn btn-primary btn-block" value="Create" />
        </div>
    </div>
}