WebLibrary/Controllers/Api/LoanController.cs
using BusinessLogic.DTOs;
using BusinessLogic.Interfaces;
using System.Web.Http;
using WebLibrary.IdentityExtensions;

namespace WebLibrary.Controllers.Api
{
    [Authorize]
    public class LoanController : ApiController
    {
        private readonly ILoanService _loanService;

        public LoanController(ILoanService loanService)
        {
            _loanService = loanService;
        }

        [HttpPost]
        public IHttpActionResult TakeLoan(LoanDto loanDto)
        {

            loanDto.UserId = User.Identity.GetUserId().Value;

            var result = _loanService.TakeLoan(loanDto);

            if (result.Success)
            {
                return Ok(result);
            }
            else
            {
                return BadRequest(result.Message);
            }

        }
        [HttpPost]
        public IHttpActionResult PayInstallment(LoanInstallmentDto installmentDto)
        {
            var result = _loanService.PayInstallment(installmentDto);
            if (result.Success)
            {
                return Ok(result);
            }
            else
            {
                return BadRequest(result.Message);
            }

        }

        [HttpGet]
        public IHttpActionResult GetLoans()
        {
            var userId = User.Identity.GetUserId().Value;
            var loans = _loanService.GetLoans(userId);
            return Ok(loans);
        }
    }
}

WebLibrary/Controllers/LoanController.cs
using BusinessLogic.Interfaces;
using System.Web.Mvc;

namespace WebLibrary.Controllers
{
    public class LoanController : Controller
    {
        private readonly ILoanService _loanService;

        public LoanController(ILoanService loanService)
        {
            _loanService = loanService;
        }

        // GET: Loan
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Loans()
        {
            return View();
        }


    }
}

WebLibrary/Views/Loan/Index.cshtml
@using System.Web.UI.HtmlControls
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script src="https://cdn.rawgit.com/JDMcKinstry/JavaScriptDateFormat/master/Date.format.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
<script src="~/Scripts/jquery-validate.bootstrap-tooltip.min.js"></script>

<div class="row mx-0">
    <div class="col-md-4 px-2 d-flex">
        <div class="jumbotron mt-5 py-5">

            <form class="ml-1" method="post" id="loanForm">
                <h3 class="display-4 mb-5" align="center">New Loan</h3>
                <label for="loanAmount">Loan amount</label>
                <div class="input-group mb-3">

                    <input type="text" class="form-control" name="loanAmount" id="loanAmount" />
                    <div class="input-group-append">
                        <span class="input-group-text">PLN</span>
                    </div>

                </div>
                <div class="input-group my-3">
                    <label for="totalInstallments">Total installments</label>
                    <input type="range" class="custom-range" id="totalInstallments" min="6" max="24" step="1" />
                    <label id="installmentInfo">installment(s)</label>
                </div>
                <label for="installmentAmount">Installment amount</label>
                <div class="input-group mb-3">
                    <input disabled="disabled" type="text" class="form-control" id="installmentAmount" />
                    <div class="input-group-append">
                        <span class="input-group-text">PLN</span>
                    </div>
                </div>

                <input type="submit" class="btn btn-primary btn-block" value="Take a loan!" />
            </form>

        </div>
    </div>
    <div class="col-md-8 px-2 d-flex">
        <div class="jumbotron mt-5 py-5">
            <h3 class="display-4 mb-3 text-center">Best loans for you!</h3>
            <div>
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
                esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt
                in culpa qui officia deserunt mollit anim id est laborum."
            </div>
            <div class="mt-3">
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit
                esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt
                in culpa qui officia deserunt mollit anim id est laborum."
                <strong>Take your loans to another level!</strong>
            </div>
            @Html.ActionLink("Go to loans", "Loans", "Loan", null, new { @class = "mt-4 btn btn-primary btn-block" })
        </div>
    </div>
</div>


<script type="text/javascript" src="~/Scripts/app/loans/index.js"></script>

WebLibrary/Views/Loan/Loans.cshtml
@{
    ViewBag.Title = "Loans";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script src="https://cdn.rawgit.com/JDMcKinstry/JavaScriptDateFormat/master/Date.format.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
<script src="~/Scripts/jquery-validate.bootstrap-tooltip.min.js"></script>


    <div class="jumbotron py-5 mt-5 mx-2 px-4">
        <h1 class="display-4 text-center mb-5">Your loans</h1>
        <table id="loans" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Loan amount</th>
                    <th>Loan amount left</th>
                    <th>Installment amount</th>
                    <th>Installments left</th>
                    <th>Next installment date</th>
                    <th>Pay installment</th>
                </tr>
            </thead>
        </table>
    </div>


<script type="text/javascript" src="~/Scripts/app/loans/loans.js"></script>