WebLibrary/Models/ViewModels/MoneyTransferViewModel.cs
namespace WebLibrary.Models.ViewModels
{
    public class MoneyTransferViewModel
    {
        public decimal CashAmount { get; set; }
        public int? FromId { get; set; }
        public int ToId { get; set; }
    }
}

WebLibrary/Controllers/Api/MoneyTransferController.cs
using BusinessLogic.DTOs;
using BusinessLogic.Interfaces;
using DataAccess.Identity;
using System.Web.Http;
using WebLibrary.IdentityExtensions;

namespace WebLibrary.Controllers.Api
{
    [Authorize]
    public class MoneyTransferController : ApiController
    {
        private readonly IMoneyTransferService _moneyTransferService;
        private readonly IApplicationUserManager _userManager;

        public MoneyTransferController(IMoneyTransferService moneyTransferService, IApplicationUserManager userManager)
        {
            _moneyTransferService = moneyTransferService;
            _userManager = userManager;
        }

        [HttpGet]
        public IHttpActionResult GetLastFive()
        {
            var userId = User.Identity.GetUserId().Value;
            var transfers = _moneyTransferService.GetLastSentFiveTransfers(userId);
            return Ok(transfers);
        }

        [HttpGet]
        public IHttpActionResult GetAllTransfers()
        {
            var userId = User.Identity.GetUserId().Value;
            var transfers = _moneyTransferService.GetAllTransfers(userId);
            return Ok(transfers);
        }

        [HttpPost]
        public IHttpActionResult Transfer(MoneyTransferDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            dto.From.Id = User.Identity.GetUserId().Value;

            var result = _moneyTransferService.Transfer(dto);


            if (!result.Success)
            {
                return BadRequest(result.Message);
            }
            else
            {
                return Ok(result.Message);
            }
        }

        [HttpGet]
        public IHttpActionResult Metadata()
        {
            var userId = User.Identity.GetUserId().Value;
            var metadata = _moneyTransferService.GetMetadata(userId);

            return Ok(metadata);
        }
    }
}

WebLibrary/Controllers/MoneyTransferController.cs
using BusinessLogic.Interfaces;
using System.Web.Mvc;
using WebLibrary.IdentityExtensions;

namespace WebLibrary.Controllers
{
    public class MoneyTransferController : Controller
    {
        private readonly IMoneyTransferService _moneyTransferService;
        private readonly IBankAccountService _bankAccountService;
        public MoneyTransferController(IMoneyTransferService moneyTransferService, IBankAccountService bankAccountService)
        {
            _moneyTransferService = moneyTransferService;
            _bankAccountService = bankAccountService;
        }

        public ActionResult Index()
        {
            ViewBag.Id = User.Identity.GetUserId().Value;
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Transfers()
        {
            ViewBag.Id = User.Identity.GetUserId().Value;
            return View();
        }

    }
}

WebLibrary/Views/MoneyTransfer/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row justify-content-center">

    <div class="col-md-4">
        <div class="jumbotron py-5">

            <form class="ml-1">
                <h3 class="display-4 mb-5" align="center">Transfer</h3>
                <label for="cashAmount">Cash amount</label>
                <div class="input-group mb-3">



                    <input type="text" class="form-control" id="cashAmount" />
                    <div class="input-group-append">
                        <span class="input-group-text">$</span>
                    </div>

                </div>

                <label for="accountNumber">Account number</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="accountNumber" />
                </div>

                <button id="submitTransfer" class="btn btn-primary btn-block">Make a transfer!</button>
            </form>

        </div>
    </div>
</div>



<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/sweetalert2.all.min.js"></script>
<script type="text/javascript" src="~/Scripts/app/moneyTransfer/create.js"></script>

WebLibrary/Views/MoneyTransfer/Index.cshtml
@using WebLibrary.IdentityExtensions
@model List<BusinessLogic.DTOs.MoneyTransferDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="row justify-content-center mt-5 visibility4">
    <div class="col-8 mb-4">
        <div class="jumbotron h-100">
        <div class="container">
            <h2 class="display-4 mb-5">Manage your transfers!</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
        </div>
        </div>
    </div>


    @Html.Partial("_PartialTransfer")


</div>

<div class="row mx-0 justify-content-center visibility4">
    <div class="col pt-4  jumbotron">

        <table id="lastTransfers" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Transfer Id</th>
                    <th>From</th>
                    <th>To</th>
                    <th>CashAmount</th>
                    <th>Date</th>
                </tr>
            </thead>
        </table>
       @Html.ActionLink("Show more!", "Transfers", "MoneyTransfer", null, new { @class = "btn btn-primary btn-block" })

    </div>
    
</div>

<script id="indexMoneyTransferScript" src="~/Scripts/app/moneyTransfer/index.js" data-userid="@ViewBag.Id"></script>

WebLibrary/Views/MoneyTransfer/Transfers.cshtml
@using WebLibrary.IdentityExtensions

@{
    ViewBag.Title = "Transfers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />*@
<div class="row mt-5 px-4 justify-content-center visibility4">
    <div class="col  pt-4 pb-1  jumbotron">
        <h2 class="display-4 mb-5 text-center">All transfers</h2>
        <table id="allTransfers" class="table table-striped table-bordered" style="width: 100%">
            <thead>
            <tr>
                <th>Name</th>
                <th>Transfer Id</th>
                <th>From</th>
                <th>To</th>
                <th>CashAmount</th>
                <th>Date</th>
            </tr>
            </thead>
        </table>
    </div>
</div>

<script id="transfersScript" src="~/Scripts/app/moneyTransfer/transfers.js" data-userid="@ViewBag.Id"></script>